In [1]:
import numpy as np

In [32]:
a = np.array([[1,2,3],[4,5,6]], dtype='int16')
b = np.array([1,2,3])
print(a)
b

[[1 2 3]
 [4 5 6]]


array([1, 2, 3])

In [11]:
#shape
print(a.shape)
b.shape

(2, 3)


(3,)

In [10]:
#dimension
print(b.ndim)
a.ndim


1


2

In [13]:
#data type
print(b.dtype)
a.dtype

int32


dtype('int32')

In [17]:
#item size
print(b.itemsize)
a.itemsize

4


2

In [23]:
#no. of elements
print(b.size)
print(a.size)
#total space taken
print(a.size*a.itemsize)
print(a.nbytes)

3
6
12
12


Accessing/ Changing specific rows,columns,elements,etc

In [36]:
c = np.array([[1,2,3,4],[5,6,7,8]])
c

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [38]:
#get specific element [r,c]
#to get 7 from above array
print(c[1,2])
c[1,-2]

7


7

In [39]:
#get specific row
c[1,:]

array([5, 6, 7, 8])

In [40]:
#get specific column
c[:,1]

array([2, 6])

In [42]:
c[0:2,1:2]

array([[2],
       [6]])

In [44]:
#[startindex:endindex:stepsize]
c[0,1:4:2]

array([2, 4])

In [45]:
c[0,0]=2

In [46]:
c

array([[2, 2, 3, 4],
       [5, 6, 7, 8]])

In [48]:
c[1,:]=[5,2,7,4]
c

array([[2, 2, 3, 4],
       [5, 2, 7, 4]])

In [52]:
c[:,1]=10
c

array([[ 2, 10,  3,  4],
       [ 5, 10,  7,  4]])

3D example

In [5]:
d = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(d)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [23]:
#get specific element
d[:,:,:]

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [24]:
#replace
d[1,1,1]=7
d

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 7]]])

In [26]:
d[:,:,1]=[[1,3],[5,7]]
d

array([[[1, 1],
        [3, 3]],

       [[5, 5],
        [7, 7]]])

In [28]:
d[:,1,:]=[[2,3],[6,7]]
d

array([[[1, 1],
        [2, 3]],

       [[5, 5],
        [6, 7]]])

In [29]:
d[1,:,:]=[[4,5],[6,7]]
d

array([[[1, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [32]:
d[0,0,0]=0
d

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

Initializing different types of array

#zreos

In [34]:
e = np.zeros(5)
e

array([0., 0., 0., 0., 0.])

In [37]:
f = np.zeros((3,2))
f

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [39]:
g = np.zeros((2,2,2))
g

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [41]:
h = np.zeros((3,3,3,3))
h

array([[[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]]])

#ones

In [43]:
i = np.ones((3,2))
i

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

#any other numbers

In [48]:
j = np.full((3,3),2)
j

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [49]:
np.full(j.shape,3)

array([[3, 3, 3],
       [3, 3, 3],
       [3, 3, 3]])

In [51]:
np.full_like(j,4)

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [52]:
j

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

Random Decimal no.

In [56]:
np.random.random_sample(j.shape)

array([[0.75305263, 0.96358564, 0.4374238 ],
       [0.11877387, 0.947639  , 0.02688778],
       [0.78641745, 0.2783058 , 0.96650044]])

In [58]:
np.random.rand(2,2)

array([[0.16033977, 0.45671386],
       [0.03682043, 0.68133445]])

In [59]:
np.random.randn(3,2)

array([[-0.32684133,  0.97869333],
       [-1.39397634,  0.21507207],
       [-0.21823578,  0.88910199]])

In [66]:
np.random.randint(0,10,size=(2,3))

array([[4, 4, 3],
       [5, 6, 8]])

identity

In [67]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [68]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [76]:
#to repeat the array
k = np.array([[1,2,3]])
l = np.repeat(k,3,axis=0)
l

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [77]:
#output required:
#1 1 1 1 1
#1 0 0 0 1
#1 0 9 0 1
#1 0 0 0 1
#1 1 1 1 1

In [84]:
m = np.ones((5,5))
print(m)
n = np.zeros((3,3))
print(n)
n[1,1] = 9
print(n)
m[1:4,1:4] = n
print(m)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


COPYING ARRAY

In [92]:
o = np.array([1,2,3])
print(o)
p = np.copy(o)
#p = o.copy() [does same as above]
print(p)
p[1]=22
print(p)
print(o)
#wrong way(necause not just copies but also changes element in original array if changed in copied array)
q = o
q[1]= 22
print(q)
print(o)

[1 2 3]
[1 2 3]
[ 1 22  3]
[1 2 3]
[ 1 22  3]
[ 1 22  3]


MATHEMATICS

In [95]:
r = np.array([1,2,3])
s = np.array([4,5,6])
r+s

array([5, 7, 9])

In [96]:
s-r

array([3, 3, 3])

In [97]:
r*s

array([ 4, 10, 18])

In [98]:
s/r

array([4. , 2.5, 2. ])

In [100]:
s//r

array([4, 2, 2], dtype=int32)

In [103]:
s**r

array([  4,  25, 216], dtype=int32)

In [104]:
r**2

array([1, 4, 9], dtype=int32)

In [105]:
np.sin(r)

array([0.84147098, 0.90929743, 0.14112001])

In [106]:
np.cos(r)

array([ 0.54030231, -0.41614684, -0.9899925 ])

In [107]:
np.tan(r)

array([ 1.55740772, -2.18503986, -0.14254654])

In [108]:
np.tanh(r)

array([0.76159416, 0.96402758, 0.99505475])

Linear Algebra

In [15]:
#matrix multiplication
t = np.ones((2,3))
u = np.full((3,4),3)
print(t,u)
v = np.matmul(t,u)
print(v,v.shape)

[[1. 1. 1.]
 [1. 1. 1.]] [[3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]]
[[9. 9. 9. 9.]
 [9. 9. 9. 9.]] (2, 4)


In [23]:
#determinant
w = np.diag([3,3,3])
print(w)
np.linalg.det(w)

[[3 0 0]
 [0 3 0]
 [0 0 3]]


27.0

In [28]:
x = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(x)
np.linalg.det(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


0.0

In [29]:
#docs.scipy.org/doc/numpy/reference/routines.linalg.html

STATISTICS

In [31]:
y = np.array([[1,2,3],[4,5,6]])

In [32]:
np.min(y)

1

In [34]:
np.min(y,axis=1)

array([1, 4])

In [36]:
np.max(y,axis=1)

array([3, 6])

In [37]:
np.sum(y)

21

In [39]:
y.sum(axis=0)
#np.sum(y,axis=0)

array([5, 7, 9])

Reorganizing array

In [40]:
#reshape
z = np.array([[1,2,3,4,5],[6,7,8,9,0]])

In [41]:
z.shape

(2, 5)

In [42]:
z.reshape(5,2)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8],
       [9, 0]])

In [43]:
np.reshape(z,(1,10))

array([[1, 2, 3, 4, 5, 6, 7, 8, 9, 0]])

In [52]:
#vertical stacking
a1 = np.array([11,12,13,14,15])
np.vstack([z,a1,z])

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9,  0],
       [11, 12, 13, 14, 15],
       [ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9,  0]])

In [56]:
#horizontal stack
a2 = np.array([[12],[13]])
np.hstack([z,a2])

array([[ 1,  2,  3,  4,  5, 12],
       [ 6,  7,  8,  9,  0, 13]])

MISCELLANEOUS

In [60]:
#Loading data from file
a3 = np.genfromtxt('data.txt',delimiter=',')
a3

array([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
       [11., 12., 13., 14., 15., 16., 17., 18., 19., 20.],
       [21., 22., 23., 24., 25., 26., 27., 28., 29., 30.]])

In [61]:
a3.astype('int32')

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30]])

In [65]:
a3.dtype

dtype('float64')

Boolean masking and advanced indexing

In [67]:
a3>=20

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [81]:
a3[a3>20]

array([21., 22., 23., 24., 25., 26., 27., 28., 29., 30.])

In [84]:
((a3>20) & (a3<25))

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [ True,  True,  True,  True, False, False, False, False, False,
        False]])

In [86]:
#not
~((a3>20) & (a3<25))

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [False, False, False, False,  True,  True,  True,  True,  True,
         True]])

In [87]:
a3[((a3>20) & (a3<25))]

array([21., 22., 23., 24.])

In [88]:
a3[~((a3>20) & (a3<25))]

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20., 25., 26., 27., 28., 29., 30.])

In [71]:
#numpy is indexable by list
a4 = np.array([1,2,3,4,5])
a4[[0,1]] 

array([1, 2])