8. SVM

classifier: 
    - Adds largest margin between support vectors of different class

9. SVM example: 

-Iris

In [11]:
from sklearn import svm, metrics
from sklearn import datasets
from sklearn.model_selection import train_test_split
import numpy as np
import pandas as pd

In [2]:
iris = datasets.load_iris()

In [7]:
#split in features and labels
X = iris.data
y = iris.target
print(X,y)
print(X.shape)
print(y.shape)
classes = ['Iris Setosa', 'Iris Versicolour', 'Iris Virginica']

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [18]:
#spliting train test data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [19]:
#creating svm model
model = svm.SVC()
#train model
model.fit(X_train, y_train)
print(model)

SVC()


In [20]:
#predictions and accuracy
predictions = model.predict(X_test)
accuracy = metrics.accuracy_score(y_test, predictions)
print("predictions: ", predictions)
print("actualvalue: ",y_test)
print("accuracy: ", accuracy)

predictions:  [0 1 0 1 1 1 2 2 1 1 1 0 1 1 0 2 2 0 0 0 1 2 2 2 1 0 1 0 1 0]
actualvalue:  [0 1 0 1 2 1 2 2 1 1 1 0 2 1 0 2 2 0 0 0 1 2 2 2 1 0 1 0 1 0]
accuracy:  0.9333333333333333


eg.: car.data

In [28]:
from sklearn import svm, metrics
from sklearn import datasets
from sklearn.model_selection import train_test_split
import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder

In [29]:
#reading car.data
data = pd.read_csv('car.data')
print(data.head())
data.describe()

  buying  maint doors persons lug_boot safety  class
0  vhigh  vhigh     2       2    small    low  unacc
1  vhigh  vhigh     2       2    small    med  unacc
2  vhigh  vhigh     2       2    small   high  unacc
3  vhigh  vhigh     2       2      med    low  unacc
4  vhigh  vhigh     2       2      med    med  unacc


buying maint doors persons lug_boot safety  class
count    1728  1728  1728    1728     1728   1728   1728
unique      4     4     4       3        3      3      4
top      high  high     4       4    small   high  unacc
freq      432   432   432     576      576    576   1210

In [30]:
#declaring features and labels
X1 = data[[
    'buying',
    'maint',
    'safety'
]].values

y1 = data[[
    'class'
]]
print(X1,y1)

[['vhigh' 'vhigh' 'low']
 ['vhigh' 'vhigh' 'med']
 ['vhigh' 'vhigh' 'high']
 ...
 ['low' 'low' 'low']
 ['low' 'low' 'med']
 ['low' 'low' 'high']]       class
0     unacc
1     unacc
2     unacc
3     unacc
4     unacc
...     ...
1723   good
1724  vgood
1725  unacc
1726   good
1727  vgood

[1728 rows x 1 columns]


In [31]:
#converting the string data to integer

#X
Le = LabelEncoder()
for i in range(len(X1[0])):
    X1[:,i] = Le.fit_transform(X1[:,i])
print(X)

#y
label_map = {
    'unacc': 0,
    'acc': 1,
    'good':2,
    'vgood':3
}
y1['class']= y1['class'].map(label_map)
y1 = np.array(y1)
print(y1)

[[3 3 1]
 [3 3 2]
 [3 3 0]
 ...
 [1 1 1]
 [1 1 2]
 [1 1 0]]
[[0]
 [0]
 [0]
 ...
 [0]
 [2]
 [3]]


In [36]:
#spliting train test data
X1_train, X1_test, y1_train, y1_test = train_test_split(X1, y1, test_size=0.2)

In [37]:
#creating svm model
model1 = svm.SVC()
#train model
model1.fit(X1_train, y1_train)
print(model1)

SVC()


In [38]:
#predictions and accuracy
predictions1 = model1.predict(X1_test)
accuracy1 = metrics.accuracy_score(y1_test, predictions1)
print("predictions: ", predictions1)
print("actualvalue: ",y1_test.values)
print("accuracy: ", accuracy1)

predictions:  [0 0 0 0 0 0 3 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 1 0 0 1 0 0 0 0
 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 3
 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 1 0 3 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 1 3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 1 0 1 0 0 0 3 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0
 0 0 0 0 0 3 1 3 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1
 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 1 0 1 0 0 0 1 1 0 0 1 1 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0
 1 0 0 0 0 0 0 0 0 0 0 1 0]
actualvalue:  [[1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [2]
 [1]
 [0]
 [0]
 [1]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [3]
 [1]
 [0]
 [1]
 [0]
 [2]
 [0]
 [1]
 [0]
 [1]
 [1]
 [0]
 [2]
 [0]
 [1]
 [0]